#Created by kiddo122

class PIDs:
	CURRENT_DATA, FREEZE_FRAME_DATA, D_T_CODES, CLEAR_D_T_CODES,
	TEST_RESULT_OXY, TEST_RESULT_OTHER, PENDING_D_T_CODES, 
	CONTROL_OP, REQUEST_INFO, PERM_D_T_CODES = range(10)
